config/routes.rb
Rails.application.routes.draw do
  resources :activities
  root "activities#index"
end

app/models/activity.rb
class Activity < ApplicationRecord
  validates :name, presence: true, length: { in: 3..50 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: %i[show edit update destroy]

  # GET /activities or /activities.json
  def index
    @activities = if params[:query.downcase].present?
                    Activity.where('name LIKE ?', "#{params[:query.downcase]}%").order('LENGTH(name) DESC').first
                  else
                    Activity.all
                  end

    if turbo_frame_request?
      render partial: 'activities', locals: { activities: @activities }
    else
      render :index
    end
  end

  # GET /activities/1 or /activities/1.json
  def show; end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit; end

  # POST /activities or /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to activity_url(@activity), notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1 or /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to activity_url(@activity), notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1 or /activities/1.json
  def destroy
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_activity
    @activity = Activity.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def activity_params
    params.require(:activity).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/_activities.html.erb
<%= turbo_frame_tag "activities" do%>
<%= render activities%>
<%end%>

app/views/activities/_activity.html.erb
<div id="<%= dom_id activity %>">
  <p>    
    <%= link_to activity.name, activity_path(activity) %>
  </p>

</div>

app/views/activities/_form.html.erb
<%= form_with(model: activity) do |form| %>
  <% if activity.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
        <% activity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render "form", activity: @activity %>

<br>

<div>
  <%= link_to "Show this activity", @activity %> |
  <%= link_to "Back to activities", activities_path %>
</div>

app/views/activities/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Perform realtime search</h1>
<%=form_with(url: activities_path, method: :get, data: {controller: "search-form", turbo_frame: "activities", turbo_action: "advance"}) do |form|%>
  <%=form.label :query, "Search by activity name"%>
    <%=form.text_field :query, data: {action: "input -> search-form#search"}%>
    <%=form.submit "Search", style: "background-color: pink; cursor: pointer; color: blue; border: none; padding: 4px; font-weight: bold"%>
<%end%><br>

<div class="new-activity">
<%= link_to "Create new search phrase", new_activity_path %>
</div>
<h1 class="search-result">Search Analytics</h1>
<div id="activities">
<%=render "activities", activities: @activities%> 
</div>

app/views/activities/new.html.erb
<h1>New Search phrase</h1>

<%= render "form", activity: @activity %>

<br>

<div>
  <%= link_to "Back to activities", activities_path %>
</div>

app/views/activities/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @activity %>

<div>
  <%= link_to "Edit this activity", edit_activity_path(@activity) %> |
  <%= link_to "Back to activities", activities_path %>

  <%= button_to "Destroy this activity", @activity, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RealtimeSearchBox</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>